### ISSUE TITLE
It's not an issue, a clarification request

### ISSUE THREAD

**Issue by irfan-cloudnix** [Qusic/TraceUtility#39]
I have used the tool to parse "Activity Monitor" instrument and to my shock I was able to see parsed data, I don't know how you achieved this, but till now I have never seen even a single bit of data extracted from Instrument's trace files across multiple tools, commands etc including your's when I tried last year. So, first of all, hats off to you for achieving this.
Now the problem I'm facing is to identify the columns compared to the extracted data.
I have created below sheet pertaining data along with few of the headers I was able to identify compared to the trace file.

Parsed Sheet :
https://docs.google.com/spreadsheets/d/16xl9VLEVCgjDb1VfSYAtyb3an0Dixug_wu5ltc3wUO0/edit?usp=sharing

Trace File : 
https://drive.google.com/file/d/1dkNxflP93_WxXSOmyrIIiCZH9RbUrR3w/view?usp=sharing

**Comment by Qusic** [comment]
right click the table header in Instruments. I guess some columns are hidden by default.

**Comment by irfan-cloudnix** [comment]
I had already enabled all the options, but few of the extracted data points are not understandable.

<img width="1440" alt="Screen Shot 2019-09-09 at 11 46 00 AM" src="https://user-images.githubusercontent.com/13532915/64507342-240c0280-d2f8-11e9-8f43-44340ca31039.png">

Refer the example below,

<img width="1440" alt="Screen Shot 2019-09-09 at 11 46 07 AM" src="https://user-images.githubusercontent.com/13532915/64507146-8a445580-d2f7-11e9-9251-7ef7eb12b85b.png">

Matching CPU usage and CPU time for a specific timestamp, I was able extract few of the column headers, but if you notice in the graph data, there are lot of headers whose data points are not matching the extracted data(Since the graph on Instruments showcases the whole device usage & not app specific). Hence I was unable to match those column headers.

Request to please suggest any other way to identify the data points from the extracted data.

Thanks & Regards

**Comment by irfan-cloudnix** [comment]
Thanks for your reply, I was able to finally identify the columns using one of the schemas available within the trace file.

<img width="1440" alt="Screen Shot 2019-09-09 at 12 17 00 PM" src="https://user-images.githubusercontent.com/13532915/64508726-c083d400-d2fb-11e9-86c4-88ffabc15660.png">

This was exactly matching the number of columns from the extracted data.

**Comment by Qusic** [comment]
I don't have time to look into this and I am afraid this can be a difficult question.

`XRAnalysisCoreReadCursorColumnCount` and `XRAnalysisCoreReadCursorGetValue` functions are in `XRAnalysisCore`, which is a quite low-level in the whole thing (kind of like the CoreData or some ORM framework in a typical app). There is still some distance between it and the graphs and tables presented by Instrument.app, where a lot of data processing, calculating or summarizing can happen.

As for the internal metadata about the columns, I think you can try looking into `fullTextSearchSpec`. Since it can format column values, it must have some information about the data type of columns and fortunately ids or names that can give you hints about what they are about.
